### ISSUE TITLE
about the number of stacked modules

### ISSUE THREAD

**Issue by qiuzidian** [QinSY123/2024-MambaVC#6]
Hello, I would like to ask two questions. Firstly, regarding the number of stacked modules, according to the paper, L3=9 on the encoding and decoding ends, but L3=2 and L2=9 on the decoder in the source code? Another question is the required cuda memory for training. As I know, the SSM structure requires more cuda memory under the same flops?

**Comment by QinSY123** [comment]
The depths array is reversed in the decoder, so L3 still corresponds to 9; for training, approximately 40GB of memory is required when the batch size is 8.

**Comment by qiuzidian** [comment]
Thank you for your answer!
